name: Force Sync Fork

on:
  schedule:
    - cron: "0 16 * * *"  # 每天北京时间 0 点（UTC+8）
  workflow_dispatch:       # 可手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/wulukewu/noip-renewer-github.git
          git fetch upstream

      - name: Hard reset to upstream
        run: |
          git checkout main   # 如果默认分支叫 master 就改成 master
          git reset --hard upstream/main

      - name: Push changes
        run: |
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
